name: Daniel Salvagni
description: personal blog
meta_description: "Personal thoughts"
author: Daniel Salvagni
email: danielsalvagni@gmail.com
twitter_username: danielsalvagni
github_username: dsalvagni

sass:
  style: compressed

markdown: redcarpet
highlighter: rouge
cover: true
logo: http://gravatar.com/avatar/56229dfef94a5a06461a7861cad15fc3/?s=100&d=mm
paginate: 15
baseurl: /
domain_name: 'http://dsalvagni.com.br'
google_analytics: 'UA-38161905-1'

plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://dsalvagni.com.br'
author:         'Daniel Salvagni'
